name: Send Email on New MSI File

on:
  push:
    paths:
      - "**/*.md"  # Trigger only when an MSI file is pushed
    branches:
      - main  # Adjust if your default branch is different

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
       
    - name: Test TLS Connection
      run: |
        openssl s_client -starttls smtp -connect smtp.gmail.com:587 -tls1_3

    - name: Send Email via Gmail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: "🚀 New Brizy Insights Released to Repository"
        html_body: file://notes.md
        to: ${{ secrets.EMAIL_RECIPIENT }}
        from: "Brizy Insights <support@brizy.com>"
        secure: false

    - name: Debug Email Step
      run: echo "Email sent successfully!"
